import { BaseLayer } from '../types';

// Comprehensive set of FREE, key-less, open tile layers (OSM family + Esri
// public reference services). No API keys, no billing, no rate-limit tokens.
export const BASE_LAYERS: BaseLayer[] = [
  {
    id: 'osm-standard',
    name: 'OpenStreetMap',
    nameAr: 'الخريطة القياسية',
    category: 'streets',
    url: 'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    subdomains: 'abc',
    attribution: '© OpenStreetMap contributors',
    maxZoom: 19,
    preview: '#8bc98b',
  },
  {
    id: 'osm-hot',
    name: 'Humanitarian OSM',
    nameAr: 'الإنسانية (HOT)',
    category: 'streets',
    url: 'https://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png',
    subdomains: 'abc',
    attribution: '© OpenStreetMap contributors, HOT',
    maxZoom: 19,
    preview: '#f2994a',
  },
  {
    id: 'osm-france',
    name: 'OSM France',
    nameAr: 'فرنسا (OSM-FR)',
    category: 'streets',
    url: 'https://{s}.tile.openstreetmap.fr/osmfr/{z}/{x}/{y}.png',
    subdomains: 'abc',
    attribution: '© OpenStreetMap France',
    maxZoom: 20,
    preview: '#d97b8e',
  },
  {
    id: 'carto-voyager',
    name: 'Carto Voyager',
    nameAr: 'فوياجر الملون',
    category: 'streets',
    url: 'https://{s}.basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}{r}.png',
    subdomains: 'abcd',
    attribution: '© CARTO, © OpenStreetMap contributors',
    maxZoom: 20,
    preview: '#f0e4c8',
  },
  {
    id: 'cyclosm',
    name: 'CyclOSM',
    nameAr: 'مسارات الدراجات',
    category: 'streets',
    url: 'https://{s}.tile-cyclosm.openstreetmap.fr/cyclosm/{z}/{x}/{y}.png',
    subdomains: 'abc',
    attribution: '© CyclOSM, © OpenStreetMap contributors',
    maxZoom: 20,
    preview: '#8ecae6',
  },
  {
    id: 'esri-satellite',
    name: 'Esri World Imagery',
    nameAr: 'قمر صناعي (Esri)',
    category: 'satellite',
    url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
    attribution: '© Esri, Maxar, Earthstar Geographics',
    maxZoom: 23,
    preview: '#3a4a3a',
  },
  {
    id: 'esri-topo',
    name: 'Esri World Topo',
    nameAr: 'الطبوغرافية (Esri)',
    category: 'topo',
    url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}',
    attribution: '© Esri, Garmin, USGS',
    maxZoom: 19,
    preview: '#c9b896',
  },
  {
    id: 'opentopomap',
    name: 'OpenTopoMap',
    nameAr: 'خطوط الكنتور',
    category: 'topo',
    url: 'https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',
    subdomains: 'abc',
    attribution: '© OpenTopoMap (CC-BY-SA), SRTM',
    maxZoom: 17,
    preview: '#b5c99a',
  },
  {
    id: 'esri-relief',
    name: 'Esri Shaded Relief',
    nameAr: 'التضاريس المظللة',
    category: 'topo',
    url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Shaded_Relief/MapServer/tile/{z}/{y}/{x}',
    attribution: '© Esri',
    maxZoom: 13,
    preview: '#d8c9a3',
  },
  {
    id: 'esri-natgeo',
    name: 'Esri NatGeo',
    nameAr: 'ناشونال جيوغرافيك',
    category: 'other',
    url: 'https://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/{z}/{y}/{x}',
    attribution: '© Esri, National Geographic',
    maxZoom: 16,
    preview: '#e3d3ab',
  },
  {
    id: 'esri-street',
    name: 'Esri Streets',
    nameAr: 'شوارع (Esri)',
    category: 'streets',
    url: 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}',
    attribution: '© Esri, HERE, Garmin',
    maxZoom: 19,
    preview: '#f4e9d8',
  },
  {
    id: 'carto-positron',
    name: 'Carto Positron',
    nameAr: 'فاتح بسيط',
    category: 'light-dark',
    url: 'https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',
    subdomains: 'abcd',
    attribution: '© CARTO, © OpenStreetMap contributors',
    maxZoom: 20,
    preview: '#f5f5f5',
  },
  {
    id: 'carto-dark',
    name: 'Carto Dark Matter',
    nameAr: 'داكن ليلي',
    category: 'light-dark',
    url: 'https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png',
    subdomains: 'abcd',
    attribution: '© CARTO, © OpenStreetMap contributors',
    maxZoom: 20,
    preview: '#1a1a2e',
  },
  {
    id: 'wikimedia',
    name: 'Wikimedia Maps',
    nameAr: 'خرائط ويكيميديا',
    category: 'other',
    url: 'https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png',
    attribution: '© Wikimedia, © OpenStreetMap contributors',
    maxZoom: 19,
    preview: '#dfe6e9',
  },
];

export const SATELLITE_LABELS_OVERLAY = {
  id: 'esri-labels',
  url: 'https://server.arcgisonline.com/ArcGIS/rest/services/Reference/World_Boundaries_and_Places/MapServer/tile/{z}/{y}/{x}',
  attribution: '© Esri',
};

export const CATEGORY_LABELS: Record<BaseLayer['category'], string> = {
  streets: 'شوارع',
  satellite: 'قمر صناعي',
  topo: 'طبوغرافي',
  'light-dark': 'فاتح / داكن',
  other: 'أخرى',
};

export function getLayerById(id: string): BaseLayer {
  return BASE_LAYERS.find((l) => l.id === id) ?? BASE_LAYERS[0];
}
